### ISSUE TITLE
Titles not escaped properly

### ISSUE THREAD

**Issue by bijsterz** [jbh/oc-blog-rss-plugin#4]
Having a title (maybe also content, haven't checked that) containing a `&` sign will result in bad XML
I get the following error in the validator:

```
This feed does not validate.
line 117, column 13: XML parsing error: <unknown>:117:13: not well-formed (invalid token) [help]
<title>Q&A: Floriade and the EuPC22 in Almere?</title>
```

I guess the contents of XML tags don't get properly escaped for use in XML

**Comment by jbh** [comment]
Thanks for the detailed information. It's good to see this is still actively used. I'll look into committing a fix by this weekend.

**Comment by bijsterz** [comment]
Thanks for the quick response Josh!

I noticed it is only this way with the automatically created rss.xml. It
works fine if I create a page with the rss component.


On Aug 31, 2017 17:49, "Josh Hall" <notifications@github.com> wrote:

Thanks for the detailed information. It's good to see this is still
actively used. I'll look into committing a fix by this weekend.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jbh/oc-blog-rss-plugin/issues/4#issuecomment-326338600>,
or mute the thread

**Comment by jbh** [comment]
Sorry for the delay! I had a busy few weeks. It was a simple fix.
